# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-14 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='birthday_party/images')),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
    ]
