# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-14 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='image',
            field=models.FileField(upload_to='birthday_party/images'),
        ),
    ]
